spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sweetshop
    username: user
    password: hackme
    initialization-mode: always
    schema: classpath*:database/init.sql
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
